//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int MaHA { get; set; }
        public string URL { get; set; }
        public Nullable<int> MaNT { get; set; }
    
        public virtual NhaTro NhaTro { get; set; }
    }
}
