//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaTro()
        {
            this.HinhAnh = new HashSet<HinhAnh>();
        }
    
        public int MaNT { get; set; }
        public string TenTro { get; set; }
        public string DiaChi { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<decimal> GiaPhong { get; set; }
        public Nullable<decimal> GiaDien { get; set; }
        public Nullable<decimal> GiaNuoc { get; set; }
        public string MoTa { get; set; }
        public string TienIch { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaND { get; set; }
        public string TrangThaiDuyet { get; set; }
        public string Lng { get; set; }
        public string Lat { get; set; }
        public string Tinh { get; set; }
        public string Quan { get; set; }
        public string Phuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnh { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
